name: Build project with maven & verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy files to staging directory
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact to action
      uses: actions/upload-artifact@v2.2.1
      with:
        name: HueMC-${{github.sha}}
        path: staging
